### ISSUE TITLE
Swagger schema validation errors sometimes don't provide useful information

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [nutanix/papiea#382]
In BMaaS, I have defined an entity procedure which takes no arguments. Paraphrased:

```ts
    const args = {type: 'object', properties: {}}
    machine_kind.entity_procedure('deprovision', {}, Halt_Intentful, {input: args}, {output: {}}, fn)
```

I call the entity procedure like so:

```ts
await machine.invoke_procedure('deprovision', machine, {})
```

But the entity procedure does not even get called (I have log messages at the beginning of the procedure which don't fire). Instead I get the following from papiea-engine:

```
bmaas_papiea | {"0":"Error: [{\"message\":\"Unable to validate an empty value for property: rootModel\"}]\n    at Function.fromError (/code/papiea-engine/src/errors/procedure_invocation_error.ts:26:20)\n    at Entity_API_Impl.call_procedure (/code/papiea-engine/src/entity/entity_api_impl.ts:166:44)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","level":"error","message":{"error":{"code":400,"errors":[{"message":"Unable to validate an empty value for property: rootModel"}],"message":"Procedure invocation failed."}},"timestamp":"2020-05-07T19:03:18.375Z"}
```

Presumably (I haven't checked yet and am just guessing) the problem is my output schema is an empty object. But I have no idea what `rootModel` is and the error doesn't point to the specific part of my code which is causing the problem.

I've seen this same `rootModel` error in a few other contexts—for example, when passing ill-formed metadata to the engine REST API (e.g. when trying to PUT an entity to set an intent). We should try to make this error more specific and reference the specific thing that the user actually provided which is causing the problem.

**Comment by joshua-berry-ntnx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Papiea bugs - needed for inventory](https://trello.com/c/R4fVY0ra/94-papiea-bugs-needed-for-inventory)

**Comment by joshua-berry-ntnx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Papiea issues needed for inventory-only BMaaS](https://trello.com/c/V6gmTU73/66-address-papiea-issues-needed-for-inventory-only-bmaas)
