### ISSUE TITLE
Validate SFS at provider registration time

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [nutanix/papiea#393]
I inadvertently put some invalid SFS while registering one of my provider's intent handlers. Provider registration succeeded successfully, but then trying to hit an endpoint on the affected entity kind failed with a 500.

The error reported (after de-JSON-ifying) was:

```
Error: No method in multimethod 'papiea-lib-clj.core/sfs-compiler' for dispatch value: [object Object]
    at Object.cljs.core.throw_no_method_error (/code/papiea-engine/papiea-lib-clj/papiea-lib-clj.js:1992:53)
    at cljs.core.MultiFn.c (/code/papiea-engine/papiea-lib-clj/papiea-lib-clj.js:1995:113)
    at cljs.core.MultiFn.a [as call] (/code/papiea-engine/papiea-lib-clj/papiea-lib-clj.js:2013:225)
    at Object.papiea_lib_clj.core.compile_sfs (/code/papiea-engine/papiea-lib-clj/papiea-lib-clj.js:3194:216)
    at sfs_compiler (/code/papiea-engine/src/intentful_core/sfs_compiler.ts:8:63)
    at Function.compile_sfs (/code/papiea-engine/src/intentful_core/sfs_compiler.ts:14:16)
    at BasicDiffer.diffs (/code/papiea-engine/src/intentful_core/differ_impl.ts:8:52)
    at diffs.next (<anonymous>)
    at DifferIntentfulStrategy.update (/code/papiea-engine/src/intentful_core/intentful_strategies/differ_intentful_strategy.ts:43:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I would have expected to see this failure at provider-registration time, rather than after the provider is registered and clients are making API calls. It would also be nice to know *which* SFS was invalid (and on which kind).

**Comment by joshua-berry-ntnx** [comment]
Hm... looking at this more, I'm not sure if it was in fact an SFS validation failure or some other SFS-compiler issue. Just for reference, the SFSes I have in this particular kind are:

- `cloud_id, owner`
- `used_ips.+{ip}`
- `used_ips.{ip}`
- `used_ips.-{ip}`

**Comment by Emulebest** [comment]
`cloud_id, owner` is causing the exception, I may be wrong but isn't it `[cloud_id, owner]`, @shlomi-nx please verify

**Comment by joshua-berry-ntnx** [comment]
Yes, that seemed to be it, thanks.

**Comment by shlomi-nx** [comment]
I agree that these errors should be caught at registration time.
