### ISSUE TITLE
Undefined fields are being cast to null fields which throws off the differ

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea#644]
We found a serious problem on the boundary between javascript and clojure. Apparently, on some occasions,  the differ is receiving spec and status that contains undefined fields. We couldn't see that its the case when printing them, because js "conveniently" hides them, but when transforming the data-structures to clojures using `js->clj`, all undefined fields are turned to null fields. This had the effect of showing us diffs where there were no diffs.

**Comment by shlomi-nx** [comment]
We tried to use mongo to ignore undefined (see https://mongodb.github.io/node-mongodb-native/2.2/api/MongoClient.html), but it does not seem to be well documented and I do not want to rely on them for this. This is why @nitesh-idnani1 .idnani is now writing the sanitizer. 

We should place the sanitizer directly before invoking the sfs differ, here https://github.com/nutanix/papiea/blob/dfb71930b9192723b7a1d4ddc01e6199cd23924b/papiea-engine/src/intentful_core/sfs_compiler.ts#L30-L32

I would do something like:
``` typescript
    static sanitize(ds:any): any { // remove any undefined field recursively}
    static run_sfs(compiled_sfs: any, spec: any, status: any): DiffContent[] | null {
        return run_compiled_sfs(compiled_sfs, sanitize(spec), sanitize(status))
    }
```

**Comment by shlomi-nx** [comment]
Lets also make sure we provide a better error message for the case that got us to discover this problem:
```
apiea_1   | 2021-03-01T23:43:41.414936000Z TypeError: Cannot read property '1' of undefined
papiea_1   | 2021-03-01T23:43:41.415600000Z     at DiffResolver.startDiffsResolution (/code/papiea-engine/build/intentful_engine/diff_resolver.js:189:42)
papiea_1   | 2021-03-01T23:43:41.415693000Z     at DiffResolver.resolveDiffs (/code/papiea-engine/build/intentful_engine/diff_resolver.js:170:24)
papiea_1   | 2021-03-01T23:43:41.415836000Z     at process._tickCallback (internal/process/next_tick.js:68:7)
papiea_1   | 2021-03-01T23:43:41.415953000Z TypeError: Cannot read property '1' of undefined
papiea_1   | 2021-03-01T23:43:41.416057000Z     at DiffResolver.startDiffsResolution (/code/papiea-engine/build/intentful_engine/diff_resolver.js:189:42)
papiea_1   | 2021-03-01T23:43:41.416158000Z     at DiffResolver.resolveDiffs (/code/papiea-engine/build/intentful_engine/diff_resolver.js:170:24)
papiea_1   | 2021-03-01T23:43:41.416262000Z     at process._tickCallback 
```
